//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Features/BulletService/Scripts/Input/BulletFireInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BulletFireInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BulletFireInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BulletFireInput"",
    ""maps"": [
        {
            ""name"": ""Bullet"",
            ""id"": ""a421adf4-9e24-4a0a-bef7-c939edbcc763"",
            ""actions"": [
                {
                    ""name"": ""FireBullet"",
                    ""type"": ""Button"",
                    ""id"": ""122666e1-8961-4d98-a4d0-683743a1643f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8848e980-1d91-474c-85c7-4cf54309d7e9"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""FireBullet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Bullet
        m_Bullet = asset.FindActionMap("Bullet", throwIfNotFound: true);
        m_Bullet_FireBullet = m_Bullet.FindAction("FireBullet", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bullet
    private readonly InputActionMap m_Bullet;
    private IBulletActions m_BulletActionsCallbackInterface;
    private readonly InputAction m_Bullet_FireBullet;
    public struct BulletActions
    {
        private @BulletFireInput m_Wrapper;
        public BulletActions(@BulletFireInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FireBullet => m_Wrapper.m_Bullet_FireBullet;
        public InputActionMap Get() { return m_Wrapper.m_Bullet; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BulletActions set) { return set.Get(); }
        public void SetCallbacks(IBulletActions instance)
        {
            if (m_Wrapper.m_BulletActionsCallbackInterface != null)
            {
                @FireBullet.started -= m_Wrapper.m_BulletActionsCallbackInterface.OnFireBullet;
                @FireBullet.performed -= m_Wrapper.m_BulletActionsCallbackInterface.OnFireBullet;
                @FireBullet.canceled -= m_Wrapper.m_BulletActionsCallbackInterface.OnFireBullet;
            }
            m_Wrapper.m_BulletActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FireBullet.started += instance.OnFireBullet;
                @FireBullet.performed += instance.OnFireBullet;
                @FireBullet.canceled += instance.OnFireBullet;
            }
        }
    }
    public BulletActions @Bullet => new BulletActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IBulletActions
    {
        void OnFireBullet(InputAction.CallbackContext context);
    }
}
